spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ptechdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dbteam
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 100
jwt:
  header: Authorization
  secret: index
  expirySeconds: 86400

server:
  port: 8080
