name: Java CD with Gradle

on:
  push:
    branches: [ release ]

env:
  S3_BUCKET_NAME: promptsol-bucket
  PROJECT_NAME: prompt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1
        with:
          mysql database: 'ptechdb'
          mysql user: 'dbteam'
          mysql password: '1234'

      - name: make application-prod.yml
        run: |
          cd ./src/main/resources

          touch ./application-prod.yml

          echo "${{ secrets.PROD_YML }}" >> ./application-prod.yml
        shell: bash
        

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy script
        run: cp ./scripts/*.sh ./deploy

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --application-name prompt-codedeploy-service \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name prompt-project \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip \
          --region ap-northeast-2 \
